やってみよう_実践編/chapter07/7_8_ピザ屋のページ/pizzas/urls.py
"""Defines URL patterns for pizzas."""

from django.urls import path

from . import views

app_name = 'pizzas'
urlpatterns = [
    # ホームページ
    path('', views.index, name='index'),
    # すべてのピザを表示するページ
    path('pizzas/', views.pizzas, name='pizzas'),
    # 個々のピザの詳細ページ
    path('pizza/<int:pizza_id>/', views.pizza, name='pizza'),
]

やってみよう_実践編/chapter07/7_8_ピザ屋のページ/pizzeria_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls')),
]

やってみよう_実践編/chapter07/7_8_ピザ屋のページ/pizzas/models.py
from django.db import models

class Pizza(models.Model):
    """ピザ屋で注文できるピザの種類を表す"""
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """モデルの文字列表現を返す"""
        return self.name

class Topping(models.Model):
    """ピザに乗せられるトッピング"""
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """モデルの文字列表現を返す"""
        return self.name

やってみよう_実践編/chapter07/7_8_ピザ屋のページ/pizzas/views.py
from django.shortcuts import render

from .models import Pizza

def index(request):
    """ピザ屋のホームページ"""
    return render(request, 'pizzas/index.html')

def pizzas(request):
    """すべてのピザを表示するページ"""
    pizzas = Pizza.objects.all()
    context = {'pizzas': pizzas}
    return render(request, 'pizzas/pizzas.html', context)

def pizza(request, pizza_id):
    """個々のピザの情報を表示するページ"""
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.topping_set.all()

    context = {'pizza': pizza, 'toppings': toppings}
    return render(request, 'pizzas/pizza.html', context)

やってみよう_実践編/chapter07/7_8_ピザ屋のページ/pizzas/templates/pizzas/base.html
<p>
  <a href="{% url 'pizzas:index' %}">ピザ屋のホームページ</a> - 
  <a href="{% url 'pizzas:pizzas' %}">ピザメニュー</a>
</p>

{% block content %}{% endblock content %}

やってみよう_実践編/chapter07/7_8_ピザ屋のページ/pizzas/templates/pizzas/index.html
{% extends 'pizzas/base.html' %}

{% block content %}
  <p>ピザ屋へようこそ！お好みのピザが見つかると嬉しいです :)</p>
{% endblock content %}

やってみよう_実践編/chapter07/7_8_ピザ屋のページ/pizzas/templates/pizzas/pizza.html
{% extends 'pizzas/base.html' %}

{% block content %}

  <p>ピザ: {{ pizza.name }}</p>

  <p>トッピング:</p>
  <ul>
    {% for topping in toppings %}
      <li>{{ topping.name }}</li>
    {% empty %}
      <li>このピザにはトッピングがありません。</li>
    {% endfor %}
  </ul>
  
{% endblock content %}

やってみよう_実践編/chapter07/7_8_ピザ屋のページ/pizzas/templates/pizzas/pizzas.html
{% extends 'pizzas/base.html' %}

{% block content %}
  <p>ピザメニュー</p>

  <ul>
    {% for pizza in pizzas %}
      <li>
        <a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza.name }}</a>
      </li>
    {% empty %}
      <li>まだピザの準備ができていません。</li>
    {% endfor %}
  </ul>

{% endblock content %}