やってみよう_実践編/chapter09/9_4_拡張された「学習ノート」/accounts/urls.py
"""accounts用URLパターンの定義"""

from django.urls import include, path

from . import views


app_name = 'accounts'
urlpatterns = [
    # デフォルトの認証URLを取り込む
    path('', include('django.contrib.auth.urls')),
    # ユーザー登録ページ
    path('register/', views.register, name='register'),
]

やってみよう_実践編/chapter09/9_4_拡張された「学習ノート」/learning_logs/urls.py
"""learning_logsのURLパターンの定義"""

from django.urls import path

from . import views

app_name = 'learning_logs'
urlpatterns = [
    # ホームページ
    path('', views.index, name='index'),
    # すべてのトピックを表示するページ
    path('topics/', views.topics, name='topics'),
    # 個別トピックの詳細ページ
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    # 新規トピックの追加ページ
    path('new_topic/', views.new_topic, name='new_topic'),
    # 新規記事の追加ページ
    path('new_entry/<int:topic_id>', views.new_entry, name='new_entry'),
    # 記事の編集ページ
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

やってみよう_実践編/chapter09/9_4_拡張された「学習ノート」/ll_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('learning_logs.urls')),
]

やってみよう_実践編/chapter09/9_4_拡張された「学習ノート」/accounts/models.py
from django.db import models

# Create your models here.

やってみよう_実践編/chapter09/9_4_拡張された「学習ノート」/learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
    """ユーザーが学んでいるトピックを表す"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    public = models.BooleanField(default=False)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """モデルの文字列表現を返す"""
        return self.text


class Entry(models.Model):
    """トピックに関して学んだ具体的なこと"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """モデルの文字列表現を返す"""
        return f"{self.text[:50]}..."

やってみよう_実践編/chapter09/9_4_拡張された「学習ノート」/learning_logs/forms.py
from django import forms

from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text', 'public']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

やってみよう_実践編/chapter09/9_4_拡張された「学習ノート」/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


def register(request):
    """新しいユーザーを登録する"""
    if request.method != 'POST':
        # 空のユーザー登録フォームを表示する
        form = UserCreationForm()
    else:
        # 入力済みのフォームを処理する
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # ユーザーをログインさせてホームページにリダイレクトする
            login(request, new_user)
            return redirect('learning_logs:index')

    # 空または無効のフォームを表示する
    context = {'form': form}
    return render(request, 'registration/register.html', context)

やってみよう_実践編/chapter09/9_4_拡張された「学習ノート」/learning_logs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Topic, Entry
from .forms import TopicForm, EntryForm


def index(request):
    """学習ノートのホームページ"""
    return render(request, 'learning_logs/index.html')

def topics(request):
    """現在のユーザーのすべてのトピックを表示し、他のユーザーのトピックのうち
    公開されたものを表示する。
    """
    # 適切なトピックをすべて取得する。
    # もしユーザーがログインしていたら、そのユーザのすべてのトピックと、
    # 他のユーザからのすべての公開トピックを取得。
    # ユーザーがログインしていない場合, 全ての公開トピックを取得。
    if request.user.is_authenticated:
        topics = Topic.objects.filter(owner=request.user).order_by('date_added')
        # 現在のユーザーが所有していない公開トピックをすべて取得する。
        # 注: クエリーを括弧で囲むことで、長いクエリーを複数行に分割することが
        # できます。
        public_topics = (Topic.objects
            .filter(public=True)
            .exclude(owner=request.user)
            .order_by('date_added'))
    else:
        # ユーザーは認証されていないのですべての公開トピックを返す。
        topics = None
        public_topics = Topic.objects.filter(public=True).order_by('date_added')

    context = {'topics': topics, 'public_topics': public_topics}
    return render(request, 'learning_logs/topics.html', context)

def topic(request, topic_id):
    """1つのトピックとそれについてのすべての記事を表示"""
    topic = Topic.objects.get(id=topic_id)

    # 現在のユーザーがこのトピックを所有している場合にのみ
    # new_entryとedit_entryのリンクを表示したい。
    is_owner = False
    if request.user == topic.owner:
        is_owner = True

    # トピックが他の人のもので、かつ公開されていない場合、
    # エラーページを表示する。
    if (topic.owner != request.user) and (not topic.public):
        raise Http404

    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries, 'is_owner': is_owner}
    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    """新規トピックを追加する"""
    if request.method != 'POST':
        # データは送信されていないので空のフォームを生成する
        form = TopicForm()
    else:
        # POSTでデータが送信されたのでこれを処理する
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('learning_logs:topics')

    # 空または無効のフォームを表示する
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """特定のトピックに新規記事を追加する"""
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        # データは送信されていないので空のフォームを生成する
        form = EntryForm()
    else:
        # POSTでデータが送信されたのでこれを処理する
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)

    # 空または無効のフォームを表示する
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """既存の記事を編集する"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # 初回リクエスト時は現在の記事の内容がフォームに埋め込まれている
        form = EntryForm(instance=entry)
    else:
        # POSTでデータが送信されたのでこれを処理する
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

やってみよう_実践編/chapter09/9_4_拡張された「学習ノート」/learning_logs/templates/learning_logs/base.html
<!doctype html>
<html lang="ja">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>学習ノート</title>

  {% load django_bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}

</head>
<body>
  <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'learning_logs:index' %}">
          学習ノート</a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
        data-bs-target="#navbarCollapse" aria-controls="navbarCollapse"
        aria-expanded="false" aria-label="ナビゲーションの切り替え">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'learning_logs:topics' %}">
              トピック一覧</a></li>
        </ul> <!-- navbar左側のリンクリストの終了 -->

        <!-- アカウント関連のリンク -->
        <ul class="navbar-nav ms-auto mb-2 mb-md-0">

          {% if user.is_authenticated %}
            <li class="nav-item">
              <span class="navbar-text me-2">こんにちは {{ user.username }}さん
                </span></li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:register' %}">
                  ユーザー登録</a></li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:login' %}">
                  ログイン</a></li>
          {% endif %}

        </ul> <!-- アカウント関連のリンクの終了 -->

        {% if user.is_authenticated %}
          <form action="{% url 'accounts:logout' %}" method='post'>
            {% csrf_token %}
            <button name='submit' class='btn btn-outline-secondary btn-sm'>
                ログアウト</button>
          </form>
        {% endif %}

      </div> <!-- navbarの折りたたみ可能なパーツの終了 -->

    </div> <!-- navbarコンテナの終了 -->
  </nav> <!-- navbar全体の終了 -->

  <main class="container">
    <div class="pb-2 mb-2 border-bottom">
      {% block page_header %}{% endblock page_header %}
    </div>

    <div>
      {% block content %}{% endblock content %}
    </div>
  </main>

</body>
</html>

やってみよう_実践編/chapter09/9_4_拡張された「学習ノート」/learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

  <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

  <p>記事を編集:</p>

  <form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_div }}
    <button name="submit">記事を更新</button>
  </form>

{% endblock content %}

やってみよう_実践編/chapter09/9_4_拡張された「学習ノート」/learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
  <div class="p-3 mb-4 bg-light border rounded-3">
    <div class="container-fluid py-4">
      <h1 class="display-3">学んだことを記録しよう</h1>

      <p class="lead">自分だけの学習ノートを作成して、学んだことをいつでも
         振り返れるようにしよう。<br>
         何か新しいことを学んだら、その内容を要約した記事を書こう。</p>

      <a class="btn btn-primary btn-lg mt-1"
        href="{% url 'accounts:register' %}">登録する &raquo;</a>
    </div>
  </div>
{% endblock page_header %}

やってみよう_実践編/chapter09/9_4_拡張された「学習ノート」/learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

  <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

  <p>新しい記事を追加:</p>
  <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_div }}
    <button name='submit'>記事を追加</button>
  </form>

{% endblock content %}

やってみよう_実践編/chapter09/9_4_拡張された「学習ノート」/learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load django_bootstrap5 %}

{% block page_header %}
  <h2>新規トピックを追加</h2>
{% endblock page_header %}

{% block content %}

  <p>トピック:</p>
  <form action="{% url 'learning_logs:new_topic' %}" method='post'>
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="トピックを追加" %}
  </form>

{% endblock content %}

やってみよう_実践編/chapter09/9_4_拡張された「学習ノート」/learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
  <h1>{{ topic.text }}</h1>
{% endblock page_header %}

{% block content %}

  {% if is_owner %}
  <p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">新しい記事を追加</a>
  </p>
  {% endif %}

  {% for entry in entries %}
    <div class="card mb-3">
      <!-- カードの見出し。作成日時と編集用のリンクを含む -->
      <h4 class="card-header">
        {{ entry.date_added|date:'Y年m月d日 H:i' }}
        {% if is_owner %}
        <small><a href="{% url 'learning_logs:edit_entry' entry.id %}">
          記事を編集</a></small>
        {% endif %}
      </h4>
      <!-- カードの本体。記事の本文を含む -->
      <div class="card-body">{{ entry.text|linebreaks }}</div>
    </div>
  {% empty %}
    <p>このトピックにはまだ記事がありません。</p>
  {% endfor %}

{% endblock content %}

やってみよう_実践編/chapter09/9_4_拡張された「学習ノート」/learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
  <h1>トピック一覧</h1>
{% endblock page_header %}

{% block content %}

  <!-- ユーザーがログインしていたら、「自分のトピック」を表示する -->
  {% if user.is_authenticated %}
    <ul class="list-group border-bottom pb-2 mb-4">
      <h5>自分のトピック:</h5>
      {% for topic in topics %}
        <li class="list-group-item border-0">
          <a href="{% url 'learning_logs:topic' topic.id %}">
            {{ topic.text }}</a>
        </li>
      {% empty %}
        <li class="list-group-item border-0">トピックはまだ作成されていません。</li>
      {% endfor %}
    </ul>
  {% endif %}

  <ul class="list-group border-bottom pb-2 mb-4">
    <h5>Public topics:</h5>
    {% for topic in public_topics %}
      <li class="list-group-item border-0">
        <a href="{% url 'learning_logs:topic' topic.id %}">
          {{ topic.text }}</a>
      </li>
    {% empty %}
      <li class="list-group-item border-0">トピックはまだ作成されていません。</li>
    {% endfor %}
  </ul>

  <a href="{% url 'learning_logs:new_topic' %}">新規トピックを追加</a>

{% endblock content %}