やってみよう_実践編/chapter09/9_3_公開ブログ/accounts/urls.py
"""accounts用URLパターンの定義"""

from django.urls import path, include

from . import views

app_name = 'accounts'
urlpatterns = [
    # デフォルトの認証URLを取り込む
    path('', include('django.contrib.auth.urls')),
    # ユーザー登録ページ
    path('register/', views.register, name='register'),
]

やってみよう_実践編/chapter09/9_3_公開ブログ/blog_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('blogs.urls')),
]

やってみよう_実践編/chapter09/9_3_公開ブログ/blogs/urls.py
"""Defines URL patterns for blogs."""

from django.urls import path

from . import views

app_name = 'blogs'
urlpatterns = [
    # ホームページ
    path('', views.index, name='index'),
    # 作成されたすべてのブログを表示するページ
    path('blogs/', views.blogs, name='blogs'),
    # 個別のブログとそのすべての投稿を表示するページ
    path('blog/<int:blog_id>/', views.blog, name='blog'),

    # 新規ブログの作成ページ
    path('new_blog/', views.new_blog, name='new_blog'),
    # 新規投稿の作成ページ
    path('new_post/<int:blog_id>/', views.new_post, name='new_post'),
    # 既存の投稿の編集ページ
    path('edit_post/<int:post_id>/', views.edit_post, name='edit_post'),
]

やってみよう_実践編/chapter09/9_3_公開ブログ/blogs/models.py
from django.db import models
from django.contrib.auth.models import User

class Blog(models.Model):
    """個人または組織のブログを表す"""
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """ブログの文字列表現を返す"""
        return self.name

class BlogPost(models.Model):
    """個別の投稿を表す"""
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    
    title = models.CharField(max_length=500)
    body = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """投稿の文字列表現を返す"""
        if len(self.title) > 50:
            return f"{self.title[:50]}..."
        else:
            return self.title

やってみよう_実践編/chapter09/9_3_公開ブログ/blogs/forms.py
from django import forms

from .models import Blog, BlogPost


class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['name']
        labels = {'name': ''}

class BlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'body']

        widgets = {'body': forms.Textarea(attrs={'cols': 80})}

やってみよう_実践編/chapter09/9_3_公開ブログ/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


def register(request):
    """新しいユーザーを登録する"""
    if request.method != 'POST':
        # 空のユーザー登録フォームを表示する
        form = UserCreationForm()
    else:
        # 入力済みのフォームを処理する
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # ユーザーをログインさせてホームページにリダイレクトする.
            login(request, new_user)
            return redirect('blogs:index')

    # 空または無効のフォームを表示する
    context = {'form': form}
    return render(request, 'registration/register.html', context)

やってみよう_実践編/chapter09/9_3_公開ブログ/blogs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Blog, BlogPost
from .forms import BlogForm, BlogPostForm


def index(request):
    """ブログのホームページ"""
    return render(request, 'blogs/index.html')

def blogs(request):
    """作成されたすべてのブログを表示するページ"""
    blogs = Blog.objects.all()
    context = {'blogs': blogs}
    return render(request, 'blogs/blogs.html', context)

def blog(request, blog_id):
    """個別のブログとそのすべての投稿を表示するページ"""
    blog = Blog.objects.get(id=blog_id)
    posts = blog.blogpost_set.all()

    context = {'blog': blog, 'posts': posts}
    return render(request, 'blogs/blog.html', context)

@login_required
def new_blog(request):
    """新規ブログの作成ページ"""
    if request.method != 'POST':
        # データは送信されていないので空のフォームを生成する
        form = BlogForm()
    else:
        # POSTでデータが送信されたのでこれを処理する
        form = BlogForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogs:blogs')

    # 空または無効のフォームを表示する
    context = {'form': form}
    return render(request, 'blogs/new_blog.html', context)

@login_required
def new_post(request, blog_id):
    """新規投稿の作成ページ"""
    blog = Blog.objects.get(id=blog_id)
    check_blog_owner(blog, request.user)

    if request.method != 'POST':
        # データは送信されていないので空のフォームを生成する
        form = BlogPostForm()
    else:
        # POSTでデータが送信されたのでこれを処理する
        form = BlogPostForm(data=request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.blog = blog
            new_post.save()
            return redirect('blogs:blog', blog_id=blog_id)

    # 空または無効のフォームを表示する
    context = {'blog': blog, 'form': form}
    return render(request, 'blogs/new_post.html', context)

@login_required
def edit_post(request, post_id):
    """既存の投稿の編集ページ"""
    post = BlogPost.objects.get(id=post_id)
    blog = post.blog
    check_blog_owner(blog, request.user)

    if request.method != 'POST':
        # 初回リクエスト時は現在の投稿の内容がフォームに埋め込まれている
        form = BlogPostForm(instance=post)
    else:
        # POSTでデータが送信されたのでこれを処理する
        form = BlogPostForm(instance=post, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogs:blog', blog_id=blog.id)

    context = {'post': post, 'blog': blog, 'form': form}
    return render(request, 'blogs/edit_post.html', context)

def check_blog_owner(blog, user):
    """Make sure the currently logged-in user owns the blog that's 
    being requested.

    Raise Http404 error if the user does not own the blog.
    """
    if blog.owner != user:
        raise Http404

やってみよう_実践編/chapter09/9_3_公開ブログ/blogs/templates/blogs/base.html
<!doctype html>
<html lang="ja">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>ブログサービス</title>

  {% load django_bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}

</head>
<body>
  <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'blogs:index' %}">
          ブログサービス</a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
        data-bs-target="#navbarCollapse" aria-controls="navbarCollapse"
        aria-expanded="false" aria-label="ナビゲーションの切り替え">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'learning_logs:topics' %}">
              ブログ一覧</a></li>
        </ul> <!-- navbar左側のリンクリストの終了 -->

        <!-- アカウント関連のリンク -->
        <ul class="navbar-nav ms-auto mb-2 mb-md-0">

          {% if user.is_authenticated %}
            <li class="nav-item">
              <span class="navbar-text me-2">こんにちは {{ user.username }}さん
                </span></li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:register' %}">
                  ユーザー登録</a></li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:login' %}">
                  ログイン</a></li>
          {% endif %}

        </ul> <!-- アカウント関連のリンクの終了 -->

        {% if user.is_authenticated %}
          <form action="{% url 'accounts:logout' %}" method='post'>
            {% csrf_token %}
            <button name='submit' class='btn btn-outline-secondary btn-sm'>
                ログアウト</button>
          </form>
        {% endif %}

      </div> <!-- navbarの折りたたみ可能なパーツの終了 -->

    </div> <!-- navbarコンテナの終了 -->
  </nav> <!-- navbar全体の終了 -->

  <main class="container">
    <div class="pb-2 mb-2 border-bottom">
      {% block page_header %}{% endblock page_header %}
    </div>

    <div>
      {% block content %}{% endblock content %}
    </div>
  </main>

</body>
</html>

やってみよう_実践編/chapter09/9_3_公開ブログ/blogs/templates/blogs/blog.html
{% extends 'blogs/base.html' %}

{% block page_header %}
  <h1>{{ blog.name }}</h1>
{% endblock page_header %}

{% block content %}

  <p>
    <a href="{% url 'blogs:new_post' blog.id %}">新規投稿</a>
  </p>

{% for post in posts %}
    <div class="card mb-3">
      <!-- カードの見出し。作成日時と編集用のリンクを含む -->
      <h4 class="card-header">{{ post.title }}</h4>
      <div class="card-body">
        <!-- カードの本体。記事の本文を含む -->
        <p class="card-text">{{ post.body|linebreaks }}</p>
        <p class="text-end">{{ post.date_added|date:'Y年m月d日 H:i' }}</p>
      </div>
      <div class="card-footer text-muted">
        <p class="text-end"><a href="{% url 'blogs:edit_post' post.id %}">
          edit post</a></p>
      </div>
    </div>
  {% empty %}
    <p>このブログにはまだ投稿がありません</p>
  {% endfor %}

{% endblock content %}

やってみよう_実践編/chapter09/9_3_公開ブログ/blogs/templates/blogs/blogs.html
{% extends 'blogs/base.html' %}

{% block page_header %}
  <h1>ブログ一覧</h1>
{% endblock page_header %}

{% block content %}

  <ul class="list-group border-bottom pb-2 mb-4">
    {% for blog in blogs %}
      <li class="list-group-item border-0">
        <a href="{% url 'blogs:blog' blog.id %}">
          {{ blog.name }}</a>
      </li>
    {% empty %}
      <li class="list-group-item border-0">まだブログが作成されていません。</li>
    {% endfor %}
  </ul>

  <a href="{% url 'blogs:new_blog' %}">新しいブログをはじめる</a>

{% endblock content %}

やってみよう_実践編/chapter09/9_3_公開ブログ/blogs/templates/blogs/edit_post.html
{% extends "blogs/base.html" %}
{% load django_bootstrap5 %}

{% block page_header %}
  <h2>投稿を編集</h2>
{% endblock page_header %}

{% block content %}

  <p><a href="{% url 'blogs:blog' blog.id %}">{{ blog.name }}</a></p>

  <form action="{% url 'blogs:edit_post' post.id %}" method='post'>
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="変更を保存" %}
  </form>

{% endblock content %}

やってみよう_実践編/chapter09/9_3_公開ブログ/blogs/templates/blogs/index.html
{% extends 'blogs/base.html' %}

{% block page_header %}
  <div class="p-3 mb-4 bg-light border rounded-3">
    <div class="container-fluid py-4">
      <h1 class="display-3">ブログサービス</h1>
      
      <p class="lead">ブログサービスで自分のブログを作り、世界中に発信できます。</p>

      <a class="btn btn-primary btn-lg mt-1"
          href="{% url 'accounts:register' %}">登録する &raquo;</a>
    </div>
  </div>
{% endblock page_header %}

やってみよう_実践編/chapter09/9_3_公開ブログ/blogs/templates/blogs/new_blog.html
{% extends "blogs/base.html" %}
{% load django_bootstrap5 %}

{% block page_header %}
  <h2>新規ブログを作成</h2>
{% endblock page_header %}

{% block content %}

  <form action="{% url 'blogs:new_blog' %}" method='post'>
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="ブログを作成" %}
  </form>

{% endblock content %}

やってみよう_実践編/chapter09/9_3_公開ブログ/blogs/templates/blogs/new_post.html
{% extends "blogs/base.html" %}
{% load django_bootstrap5 %}

{% block page_header %}
  <h2>新しい投稿を作成</h2>
{% endblock page_header %}

{% block content %}

  <p><a href="{% url 'blogs:blog' blog.id %}">{{ blog.name }}</a></p>

  <form action="{% url 'blogs:new_post' blog.id %}" method='post'>
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="投稿を作成" %}
  </form>

{% endblock content %}